# Generated by Django 4.2.2 on 2023-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='user',
        ),
        migrations.AddField(
            model_name='extension',
            name='Length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extension',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
