# Generated by Django 4.2.2 on 2023-07-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_extension_user_extension_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extension',
            old_name='Length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='extension',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
