# Generated by Django 4.2.2 on 2023-07-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_length_extension_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
