# Generated by Django 4.2.2 on 2023-07-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_order_orderitem_product_delete_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='', upload_to='main_app/images/'),
        ),
    ]
